apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gr0r0tbs8-dotnet-basic
  janus-idp.io/tekton: gr0r0tbs8-dotnet-basic
  backstage.io/kubernetes-id: gr0r0tbs8-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gr0r0tbs8-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
